bypass_group:
  - vinicius3516

freezing_dates:
  End of the year:
    from: 2025-12-24
    to: 2026-01-10

  Carnival:
    from: 2026-03-18
    to: 2026-02-22

  Test:
    from: 2025-08-25
    to: 2025-08-30
